### ISSUE TITLE
Problems of QTRAN

### ISSUE THREAD

**Issue by lylyjy** [puyuan1996/MARL#1]
In QTRAN, is global state available? Thanks.

**Comment by puyuan1996** [comment]
Sorry for the late reply. In the QTRAN paper, the author is only experimenting on Matrix game, Multi-domain Gaussian Squeeze (MGZ) and Modified Predator-prey (MPP). In the Appendix C.1. Environment,

- about MGZ, the paper described as,

> This task covers a fully observable case where all agents can see the entire state.


- about MPP,  the paper described as,

> Each agent’s observation includes its own coordinates, agent ID, and the coordinates of the prey relative to itself, if observed. 

So I speculate that in MGZ the global state is  available and used, but in MPP, the global state is not available and not used.
